define([GCC],[gcc])
define([GCC_VERSION],[14.3.1])
define([NO_CF_PROTECT],[-fcf-protection=none])
define([NAKED],[__attribute__((naked))])
define([SRC_PATH],[/home/matheussines/Documentos/GRADUAÇÃO/SO2/mfDOS/so2-fernando-e-matheus])
